catch(e) {
    console.log("Error creating the array - giving up");
} 