try {
    var a = Array(-1);
} retry(5, RangeError) {
    console.log("Error creating the array - retrying");
} catch(e) {
    console.log("Error creating the array - giving up");
} finally {
    console.log("Done");
}